Small fix. Refactor
onCreate() may be returned before super.onCreate() called. might cause:
android.util.SuperNotCalledException: Activity did not call through to super.onCreate()